blank_issues_enabled: true
contact_links:
  - name: "ğŸ’¡ Request a Feature"
    about: Request a New Feature or Enhancement in the Discussions.
    url: https://github.com/cssnr/link-extractor/discussions/new?category=feature-requests

  - name: "â” Ask a Question"
    about: Ask a General Question or start a Discussions.
    url: https://github.com/cssnr/link-extractor/discussions/new?category=q-a

  - name: "ğŸ’¬ Join Discord"
    about: Chat with us about Issues, Features, Questions and More.
    url: https://discord.gg/wXy6m2X8wY

  - name: "ğŸ“ Submit Feedback"
    about: Send General Feedback Anonymously.
    url: https://cssnr.github.io/feedback
